node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('CLI workaround') {
    /* Workaround to address issue with credentials stored in Jenkins not
    * being passed correctly to the docker registry
    * - ref https://issues.jenkins-ci.org/browse/JENKINS-38018 */
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
    sh 'docker login -u $USERNAME -p $PASSWORD https://index.docker.io/v2/'
    }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("johnnyfifi/jenkins-docker-example:${commit_id}", '.').push()
     }
   }
}
